// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhxffosnpnwztblodygd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoeGZmb3NucG53enRibG9keWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzc3MDksImV4cCI6MjA1NDg1MzcwOX0.FNB6zfl4pqcCby1bL_JOt8iLN1up46in1S2qo2ZTF6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);